In [1]:
# Import Packages
import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle

In [4]:
df = pd.read_csv(r"C:\Users\zacha\龙京\python\youtube\uci_student\student-por.csv", sep = ";")

In [5]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [6]:
# Cutting Columns
df = df[["G1", "G2", "G3", "studytime", "failures", "absences"]]

In [7]:
# Assigning Target Variable
predict = ["G3"]

In [8]:
# Establishing X and Y Values
import numpy as np 
X = np.array(df.drop(predict, axis = 1))
y = np.array(df[predict])

In [11]:
# Assigning Train and Test
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

In [12]:
# Testing Model Accuracy
linear = linear_model.LinearRegression()

linear.fit(x_train, y_train)
accuracy = linear.score(x_test, y_test)
print(accuracy)

0.8957112628111725

In [15]:
# Coefficient and Intercept
print('Co: \n', linear.coef_)
print('Intercerpt: \n', linear.intercept_)

Co:
 [[ 0.13961646  0.88990851  0.10033129 -0.21483075  0.02534195]]
Intercerpt:
 [-0.20058169]

In [19]:
# Model Prediction
predictions = linear.predict(x_test)

In [20]:
for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])

[11.85543505] [13 11  4  0  2] [11]
[9.07654184] [8 9 1 0 2] [11]
[9.40645868] [10  9  1  0  4] [9]
[12.11443287] [11 12  1  0  0] [11]
[8.23628071] [8 8 2 0 0] [8]
[12.16511678] [11 12  1  0  2] [11]
[7.7430286] [7 8 2 2 3] [7]
[9.22755703] [8 9 2 0 4] [9]
[11.27554839] [10 11  1  1 16] [11]
[11.32438419] [ 9 11  2  0 11] [10]
[17.36238905] [16 17  2  0  0] [17]
[15.30333909] [14 15  2  0  0] [15]
[12.3936658] [13 12  1  0  0] [13]
[10.69976538] [10 10  3  0 12] [11]
[11.51515601] [12 11  2  0  2] [11]
[11.78204732] [11 11  1  0 22] [10]
[16.57281182] [16 16  3  0  0] [16]
[14.55304704] [15 14  2  0  0] [15]
[12.73601789] [14 12  1  0  8] [13]
[11.36414082] [12 11  1  0  0] [12]
[14.75474614] [15 14  3  0  4] [15]
[11.28764351] [10 11  1  0  8] [11]
[13.38494213] [13 13  1  0  4] [14]
[13.5856047] [13 13  3  0  4] [13]
[18.44259794] [17 18  2  0  2] [17]
[10.13140877] [ 9 10  1  0  3] [10]
[14.51376187] [14 14  3  0  0] [14]
[9.26684221] [9 9 1 0 4] [10]
[10.34705109] [10 10  1  0  6] [10]
[13.3839056] [13 13  2  0  0] [10]
[13.43458951] [13 13  2  0  2] [13]
[9.31648959] [9 9 2 0 2] [9]
[13.52352207] [14 13  2  0  0] [13]
[12.11443287] [11 12  1  0  0] [12]
[16.47248054] [16 16  2  0  0] [16]
[12.54468099] [13 12  2  0  2] [12]
[12.21580068] [11 12  1  0  4] [14]
[13.24428914] [12 13  2  0  0] [13]
[10.19499938] [10 10  1  0  0] [10]
[10.97796179] [12 10  4  0  8] [11]
[13.3839056] [13 13  2  0  0] [13]
[11.1862757] [10 11  1  0  4] [11]
[11.56583992] [12 11  2  0  4] [12]
[10.08049992] [10 10  2  1  0] [10]
[11.3879748] [10 11  2  0  8] [12]
[13.20604048] [11 13  2  0  4] [14]
[12.35438062] [12 12  2  0  0] [13]
[8.55202937] [10  8  4  1  2] [9]
[12.92424521] [15 12  3  0  2] [13]
[14.77334631] [14 15  1  2  0] [15]
[12.27788331] [10 12  2  0  8] [12]
[14.50292821] [13 14  1  0 13] [14]
[9.11409409] [8 9 2 1 8] [8]
[17.79471022] [18 17  1  0 10] [18]
[11.51619254] [12 11  1  0  6] [11]
[12.63361355] [14 12  2  0  0] [12]
[12.49399709] [13 12  2  0  0] [12]
[13.01574011] [10 13  2  0  2] [13]
[16.53456317] [15 16  3  0  4] [16]
[17.88156973] [19 17  3  0  0] [18]
[11.1862757] [10 11  1  0  4] [11]
[11.18523918] [10 11  2  0  0] [11]
[10.72661531] [12 10  2  0  6] [11]
[15.27752569] [12 15  2  0 10] [15]
[12.59432837] [13 12  3  0  0] [13]