In [134]:
import pandas as pd

In [135]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
df = pd.read_csv(r'C:\Users\zacha\Hyperborea\csv files\survey_results_public.csv')

In [11]:
df.head(5)

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,Salary
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [8]:
df.rename(columns = {'ResponseId': 'Respondent', 'ConvertedCompYearly': 'Salary'}, inplace = True)

In [10]:
df.set_index(['Respondent'], inplace = True)

In [12]:
df['Country'] = df['Country'].replace(['United States of America'], 'America')

# Start

In [21]:
# DataFrame + Description 

df.describe()

          CompTotal        Salary
count  4.718300e+04  4.684400e+04
mean   2.119407e+69  1.184262e+05
std    4.603702e+71  5.272944e+05
min    0.000000e+00  1.000000e+00
25%    1.600000e+04  2.702500e+04
50%    6.700000e+04  5.621100e+04
75%    1.400000e+05  1.000000e+05
max    1.000000e+74  4.524131e+07

In [19]:
# Column + Median 

df['Salary'].median()

56211.0

In [ ]:
# Column + Average 

df['Salary'].mean()

118426.15289044488

In [24]:
# Column + Count 

df['Salary'].count()

46844

In [25]:
# Column + Value Count

df['Country'].value_counts()

America                                                 15288
India                                                   10511
Germany                                                  5625
United Kingdom of Great Britain and Northern Ireland     4475
Canada                                                   3012
                                                        ...
Saint Kitts and Nevis                                       1
Dominica                                                    1
Saint Vincent and the Grenadines                            1
Tuvalu                                                      1
Papua New Guinea                                            1
Name: Country, Length: 181, dtype: int64

In [26]:
# Column + Value Count + Percentage 

df['Country'].value_counts(normalize = True)

America                                                 0.183224
India                                                   0.125972
Germany                                                 0.067415
United Kingdom of Great Britain and Northern Ireland    0.053632
Canada                                                  0.036098
                                                          ...
Saint Kitts and Nevis                                   0.000012
Dominica                                                0.000012
Saint Vincent and the Grenadines                        0.000012
Tuvalu                                                  0.000012
Papua New Guinea                                        0.000012
Name: Country, Length: 181, dtype: float64

In [27]:
df['Employment'].value_counts(normalize = True)

Employed full-time                                      0.643088
Student, full-time                                      0.141390
Independent contractor, freelancer, or self-employed    0.096504
Not employed, but looking for work                      0.035536
Employed part-time                                      0.029536
Student, part-time                                      0.024615
Not employed, and not looking for work                  0.014738
I prefer not to say                                     0.010681
Retired                                                 0.003912
Name: Employment, dtype: float64

In [153]:
# Create a Groupby

country_group = df.groupby(['Country'])

In [31]:
# Groupby + Value 

country_group.get_group('America')

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,Salary
Respondent,,,,,,,,,,,,,,,,,,,,,
6,I am a student who is learning to code,"Student, part-time",America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
7,I code primarily as a hobby,I prefer not to say,America,New Hampshire,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",3,NaN,...,Prefer not to say,Prefer not to say,No,NaN,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
16,I am a student who is learning to code,"Student, full-time",America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,NaN,...,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN
37,I am a developer by profession,Employed full-time,America,District of Columbia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",8,Less than 1 year,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,Prefer not to say,Too short,Easy,103000.0
38,I am a developer by profession,Employed full-time,America,Massachusetts,NaN,Some college/university study without earning ...,18 - 24 years,"Other online resources (ex: videos, blogs, etc)",20,15,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,300000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83428,I am a developer by profession,Employed full-time,America,Pennsylvania,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",13,2,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,"I have an anxiety disorder;Or, in your own words:",Too short,Easy,4300000.0
83430,I code primarily as a hobby,"Not employed, but looking for work",America,Washington,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",6,NaN,...,25-34 years old,"Man;Or, in your own words:",Yes,Queer,White or of European descent,I am unable to / find it difficult to walk or ...,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,NaN
83431,I am a developer by profession,Employed full-time,America,Illinois,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",23,21,...,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,125000.0
83435,I am a developer by profession,Employed full-time,America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83437,I am a developer by profession,Employed full-time,America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0

In [37]:
# Filter  

usa_filt = df['Country'] == 'America'

df.loc[usa_filt]

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,Salary
Respondent,,,,,,,,,,,,,,,,,,,,,
6,I am a student who is learning to code,"Student, part-time",America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
7,I code primarily as a hobby,I prefer not to say,America,New Hampshire,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",3,NaN,...,Prefer not to say,Prefer not to say,No,NaN,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
16,I am a student who is learning to code,"Student, full-time",America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,NaN,...,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN
37,I am a developer by profession,Employed full-time,America,District of Columbia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",8,Less than 1 year,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,Prefer not to say,Too short,Easy,103000.0
38,I am a developer by profession,Employed full-time,America,Massachusetts,NaN,Some college/university study without earning ...,18 - 24 years,"Other online resources (ex: videos, blogs, etc)",20,15,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,300000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83428,I am a developer by profession,Employed full-time,America,Pennsylvania,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",13,2,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,"I have an anxiety disorder;Or, in your own words:",Too short,Easy,4300000.0
83430,I code primarily as a hobby,"Not employed, but looking for work",America,Washington,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",6,NaN,...,25-34 years old,"Man;Or, in your own words:",Yes,Queer,White or of European descent,I am unable to / find it difficult to walk or ...,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,NaN
83431,I am a developer by profession,Employed full-time,America,Illinois,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",23,21,...,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,125000.0
83435,I am a developer by profession,Employed full-time,America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83437,I am a developer by profession,Employed full-time,America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0

In [39]:
# Loc + Filter + Value Count 

df.loc[usa_filt]['Employment'].value_counts()

Employed full-time                                      11214
Student, full-time                                       1689
Independent contractor, freelancer, or self-employed      976
Not employed, but looking for work                        425
Employed part-time                                        263
Not employed, and not looking for work                    244
I prefer not to say                                       185
Student, part-time                                        140
Retired                                                   130
Name: Employment, dtype: int64

In [42]:
# Filter + Value Count By Percentage 

df.loc[usa_filt]['Employment'].value_counts(normalize = True)

Employed full-time                                      0.734574
Student, full-time                                      0.110638
Independent contractor, freelancer, or self-employed    0.063933
Not employed, but looking for work                      0.027840
Employed part-time                                      0.017228
Not employed, and not looking for work                  0.015983
I prefer not to say                                     0.012118
Student, part-time                                      0.009171
Retired                                                 0.008516
Name: Employment, dtype: float64

In [60]:
# Groupby + Value Count 

country_group['Employment'].value_counts()

Country      Employment
Afghanistan  Employed full-time                                      19
             I prefer not to say                                     10
             Student, full-time                                       7
             Employed part-time                                       6
             Student, part-time                                       6
                                                                     ..
Zimbabwe     Independent contractor, freelancer, or self-employed     4
             Not employed, but looking for work                       4
             I prefer not to say                                      2
             Not employed, and not looking for work                   2
             Student, part-time                                       2
Name: Employment, Length: 1122, dtype: int64

In [65]:
# Groupby + Value Count + Head 

country_group['Employment'].value_counts().head(25)

Country      Employment
Afghanistan  Employed full-time                                      19
             I prefer not to say                                     10
             Student, full-time                                       7
             Employed part-time                                       6
             Student, part-time                                       6
             Independent contractor, freelancer, or self-employed     5
             Not employed, but looking for work                       4
             Retired                                                  4
             Not employed, and not looking for work                   3
Albania      Employed full-time                                      43
             Independent contractor, freelancer, or self-employed     7
             Not employed, and not looking for work                   5
             Student, full-time                                       5
             Not employed, but looking for work                       4
             I prefer not to say                                      3
             Employed part-time                                       2
             Student, part-time                                       2
             Retired                                                  1
Algeria      Employed full-time                                      15
             Independent contractor, freelancer, or self-employed    10
             Not employed, but looking for work                       8
             Student, full-time                                       7
             Employed part-time                                       2
             I prefer not to say                                      1
             Not employed, and not looking for work                   1
Name: Employment, dtype: int64

In [66]:
# Groupby + Column + Value Count + Loc + Value 

country_group['Employment'].value_counts().loc['China']

Employment
Employed full-time                                      650
Student, full-time                                      226
Student, part-time                                       52
Independent contractor, freelancer, or self-employed     32
Not employed, but looking for work                       32
Employed part-time                                       24
Not employed, and not looking for work                   22
I prefer not to say                                      13
Retired                                                   1
Name: Employment, dtype: int64

In [68]:
# Groupby + Value Count + Percentage + Loc + Value 

country_group['Employment'].value_counts(normalize = True).loc['China']

Employment
Employed full-time                                      0.617871
Student, full-time                                      0.214829
Student, part-time                                      0.049430
Independent contractor, freelancer, or self-employed    0.030418
Not employed, but looking for work                      0.030418
Employed part-time                                      0.022814
Not employed, and not looking for work                  0.020913
I prefer not to say                                     0.012357
Retired                                                 0.000951
Name: Employment, dtype: float64

In [76]:
race_group = df.groupby('Ethnicity')

race_group.get_group('White').head(5)

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,Salary
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,...,25-34 years old,Man,No,NaN,White,None of the above,NaN,Appropriate in length,Easy,NaN
10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,4,...,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0

In [73]:
df['Ethnicity'] = df['Ethnicity'].replace(['White or of European descent'], 'White')

In [96]:
white_filt = df['Ethnicity'] == 'White'

df.loc[white_filt]['Ethnicity'].value_counts()

White    42671
Name: Ethnicity, dtype: int64

In [138]:
# Groupby + Column + Mean + Value Counts 

country_group['Salary'].mean().sort_values(ascending = False)

Country
Afghanistan                          2794748.000
San Marino                            596700.000
America                               262993.898
North Korea                           240000.000
Nomadic                               215491.278
                                         ...
Mali                                         NaN
Micronesia, Federated States of...           NaN
Papua New Guinea                             NaN
Sierra Leone                                 NaN
Tuvalu                                       NaN
Name: Salary, Length: 181, dtype: float64

In [144]:
# Groupby + Column + Mean + Value 

country_group['Salary'].mean().loc['China']

62562.90969899666

In [147]:
# Median + Mean = Agg Function 

country_group['Salary'].agg(['median', 'mean']).loc['China']

median   34296.000
mean     62562.910
Name: China, dtype: float64

In [164]:
# Groupby + Column + Apply + Lambda + Str + Sum 

country_group['Gender'].apply(lambda x: x.str.contains('Man').sum())

Country
Afghanistan                                38
Albania                                    56
Algeria                                    41
America                                 13337
Andorra                                     8
                                        ...
Venezuela, Bolivarian Republic of...       99
Viet Nam                                  351
Yemen                                      18
Zambia                                     21
Zimbabwe                                   33
Name: Gender, Length: 181, dtype: int64

In [158]:
df[usa_filt]['Gender'].value_counts()

Man                                                                                   13185
Woman                                                                                   908
Prefer not to say                                                                       346
Non-binary, genderqueer, or gender non-conforming                                       217
Or, in your own words:                                                                   92
Man;Non-binary, genderqueer, or gender non-conforming                                    89
Woman;Non-binary, genderqueer, or gender non-conforming                                  65
Man;Or, in your own words:                                                               50
Non-binary, genderqueer, or gender non-conforming;Or, in your own words:                  7
Woman;Or, in your own words:                                                              7
Man;Woman                                                                                 6
Man;Woman;Non-binary, genderqueer, or gender non-conforming                               6
Woman;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:            6
Man;Woman;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:        1
Name: Gender, dtype: int64

In [161]:
afghan_filt = df['Country'] == 'Afghanistan'

In [162]:
df[afghan_filt]['Gender'].value_counts()

Man                                                                                   36
Or, in your own words:                                                                 5
Non-binary, genderqueer, or gender non-conforming                                      5
Woman                                                                                  4
Prefer not to say                                                                      3
Man;Woman;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:     1
Man;Non-binary, genderqueer, or gender non-conforming                                  1
Name: Gender, dtype: int64